import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coading_Buddys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Coading_Buddys</a>
        </h1>
    <Link href="/language">
        <button className={styles.button}>
      Get Started
    </button></Link>
      </main>
      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
